[package]
name = "roguelike"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sdl2 = "0.34"

[dependencies.sdl2]
features = ["bundled", "static-link"]
git = "https://github.com/rust-sdl2/rust-sdl2"